### ISSUE TITLE
Package Name Brainstorming

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/shinyClinPharmNlmixr#4]
As mentioned in #1, I agree, a different name would be preferable.

I kinda like `rxShiny` as it covers the intent and is succinct.  I could also see `rxShinySim` or `rxSimShiny`.

**Comment by mattfidler** [comment]
But it for nlmixr objects.  Maybe `nmShiny` or `nmShinySim`.  I'm not a huge fan of the `nm` prefix either since it could be confused with NONMEM.  Yet, I use it in many of the nlmixr functions.

**Comment by billdenney** [comment]
At the package name level, I agree that `nm` could be confusing.

To me, the end goal would be that either RxODE or nlmixr objects could be sources for simulation in the package, so `rx` doesn't feel off in that way.

To be a bit playful:  `mixyShiny`?

**Comment by mattfidler** [comment]
That is fine with me;  Perhaps we should try to get Bernard involved in these conversations.  I will send him another mail.

**Comment by mattfidler** [comment]
He responded that he was aware.  I guess he doesn't want to weigh in right now.

I will move this to `mixyShiny`
